---
abstract: 'Auto-inflate your decimal columns into'
author:
  - 'Christopher Mckay, C<< <potatohead at potatolan.com> >>'
  - 'Christopher Mckay <potatohead@potatolan.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-InflateColumn-BigFloat
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0
  Math::BigFloat: 0
  namespace::clean: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
